/* QuizNova — static data: categories, subjects and the question bank. */
window.QUIZ_DATA = (() => {
  // Bump when questions change, so old challenge codes can warn that questions may differ.
  const BANK_VERSION = 2;

  const CATEGORIES = [
    { id: 'edu', name: 'Educational', icon: 'book' },
    { id: 'maths', name: 'Maths', icon: 'math' },
    { id: 'comics', name: 'Comics', icon: 'mask' },
    { id: 'movies', name: 'Movies', icon: 'film' },
    { id: 'series', name: 'Series', icon: 'tv' },
    { id: 'anime', name: 'Anime', icon: 'sparkle' },
    { id: 'gaming', name: 'Gaming', icon: 'gamepad' },
    { id: 'sports', name: 'Sports', icon: 'ball' },
    { id: 'party', name: 'Party', icon: 'dice' },
  ];

  // `topic` is what the AI is asked to write about. `aiOnly` subjects have no built-in questions.
  // `hidden` subjects never appear as cards (the custom-topic slot).
  // `gen` subjects get fresh problems from js/maths.js by default (answers worked out by QuizNova); players can pick AI instead.
  // `focus` lists areas of a subject; each AI round picks a few at random so games don't keep circling the same facts.
  // `offTopic` lists names that mean an AI question is about something else (e.g. a spin-off); those questions are dropped.
  const SUBJECTS = [
    { id: 'web', name: 'HTML & CSS', category: 'edu', code: 'WEB', tagline: 'Tags, selectors and layout tricks.', topic: 'HTML and CSS for web development' },
    { id: 'js', name: 'JavaScript', category: 'edu', code: 'JS', tagline: 'Types, arrays and the event loop.', topic: 'JavaScript programming' },
    { id: 'devops', name: 'Git & DevOps', category: 'edu', code: 'OPS', tagline: 'Git, GitHub and Jenkins pipelines.', topic: 'Git, GitHub, CI/CD and Jenkins' },
    { id: 'dsa', name: 'Data Structures', category: 'edu', code: 'DSA', tagline: 'Stacks, trees and Big-O.', topic: 'data structures and algorithms' },
    { id: 'science', name: 'Science', category: 'edu', code: 'SCI', tagline: 'Atoms, cells and planets.', topic: 'general science: physics, chemistry, biology and space' },
    { id: 'geography', name: 'Geography', category: 'edu', code: 'GEO', tagline: 'Countries, capitals, rivers and landmarks.', topic: 'world geography: countries, capitals, rivers, mountains and landmarks', icon: 'globe', aiOnly: true },
    { id: 'history', name: 'History', category: 'edu', code: 'HIS', tagline: 'Empires, inventions and turning points.', topic: 'world and Indian history', icon: 'scroll', aiOnly: true },
    { id: 'math', name: 'Mathematics', category: 'maths', code: 'MTH', tagline: 'A mix of everything: sums to calculus.', topic: 'school mathematics, from arithmetic and algebra to geometry and calculus', gen: 'mix' },
    { id: 'arith', name: 'Arithmetic', category: 'maths', code: 'ARI', tagline: 'Sums, times tables, fractions and percentages.', topic: 'arithmetic: mental calculation, times tables, fractions, decimals, percentages and order of operations', gen: 'arith', icon: 'calc' },
    { id: 'algebra1', name: 'Basic Algebra', category: 'maths', code: 'ALG', tagline: 'Solve for x, simplify and expand.', topic: 'basic algebra: solving linear equations, simplifying, expanding brackets and substitution', gen: 'algebra1', icon: 'xeq' },
    { id: 'algebra', name: 'Algebra', category: 'maths', code: 'AL2', tagline: 'Quadratics, indices, logs and simultaneous equations.', topic: 'algebra: quadratic equations, factorising, indices, logarithms and simultaneous equations', gen: 'algebra', icon: 'parabola' },
    { id: 'geometry', name: 'Geometry & Trig', category: 'maths', code: 'GEO', tagline: 'Areas, angles, Pythagoras and trig values.', topic: 'geometry and trigonometry: areas, perimeters, angles, Pythagoras, circles, volumes and exact trig values', gen: 'geometry', icon: 'triangle' },
    { id: 'calculus', name: 'Calculus', category: 'maths', code: 'CAL', tagline: 'Derivatives, integrals and limits.', topic: 'calculus: derivatives, integrals and limits', gen: 'calculus', icon: 'integral' },
    { id: 'marvel', name: 'Marvel', category: 'comics', code: 'MRV', tagline: 'Avengers, Infinity Stones and Wakanda.', topic: 'Marvel comics and the Marvel Cinematic Universe' },
    { id: 'dc', name: 'DC', category: 'comics', code: 'DC', tagline: 'Gotham, Krypton and the Justice League.', topic: 'DC comics and DC films' },
    { id: 'hollywood', name: 'Hollywood', category: 'movies', code: 'HLW', tagline: 'Blockbusters, directors and iconic lines.', topic: 'Hollywood movies, actors and directors' },
    { id: 'mcu', name: 'MCU', category: 'movies', code: 'MCU', tagline: 'Marvel Cinematic Universe: the Infinity Saga and beyond.', topic: 'the Marvel Cinematic Universe (MCU): its films and Disney+ series, characters, actors, directors and the Infinity Saga' },
    { id: 'indian', name: 'Indian Cinema', category: 'movies', code: 'IND', tagline: 'Bollywood, Tollywood and beyond.', topic: 'Indian cinema: Bollywood, Tollywood, Kollywood and more' },
    { id: 'tfi', name: 'TFI', category: 'movies', code: 'TFI', tagline: 'Tier-1 heroes, their blockbusters and star directors.', topic: 'modern Telugu cinema (TFI): the tier-1 heroes Prabhas, Mahesh Babu, Jr. NTR, Allu Arjun, Ram Charan and Pawan Kalyan and their films, and star directors such as S. S. Rajamouli, Sukumar, Trivikram Srinivas, Koratala Siva, Prashanth Neel, Sandeep Reddy Vanga and Nag Ashwin. Only films from 2005 onwards: no old classics or classic-era stars',
      focus: ['Prabhas and his films', 'Mahesh Babu and his films', 'Jr. NTR and his films', 'Allu Arjun and his films', 'Ram Charan and his films', 'Pawan Kalyan and his films', 'S. S. Rajamouli’s films', 'Sukumar’s films', 'Trivikram Srinivas’s films', 'Koratala Siva, Prashanth Neel and Sandeep Reddy Vanga', 'Nag Ashwin, Anil Ravipudi, Harish Shankar and Boyapati Srinu', 'hit songs and music directors of these heroes’ films'],
      offTopic: ['mayabazar', 'pathala bhairavi', 'senior ntr', 'sr ntr', 'sr. ntr', 'akkineni nageswara rao', 'sankarabharanam', 'ghantasala', 'telugu desam'] },
    { id: 'dune', name: 'Dune', category: 'movies', code: 'DUNE', tagline: 'Arrakis, sandworms and spice: Part One and Two.', topic: 'Denis Villeneuve’s two Dune films, Dune: Part One (2021) and Dune: Part Two (2024): their story, characters, cast, places, music and making. Only these two films, not the 1984 film, the TV series or later books', icon: 'dune',
      focus: ['Dune: Part One (2021)', 'Dune: Part Two (2024)', 'House Atreides', 'House Harkonnen', 'the Fremen, Arrakis and the sandworms', 'the Bene Gesserit and the Emperor', 'the cast and who plays whom', 'Denis Villeneuve, Hans Zimmer’s music and the Oscars'],
      offTopic: ['david lynch', 'kyle maclachlan', '1984', 'dune: prophecy', 'dune prophecy', 'dune messiah', 'part three'] },
    { id: 'harrypotter', name: 'Harry Potter', category: 'movies', code: 'HP', tagline: 'Hogwarts, spells and the Wizarding World.', topic: 'the Harry Potter books and films', icon: 'sparkle', aiOnly: true },
    { id: 'starwars', name: 'Star Wars', category: 'movies', code: 'SW', tagline: 'Jedi, Sith and a galaxy far, far away.', topic: 'the Star Wars films and series', icon: 'star', aiOnly: true },
    { id: 'seriesmix', name: 'Series Mix', category: 'series', code: 'TV', tagline: 'Hit shows from Netflix, Prime and beyond.', topic: 'popular TV and streaming series from around the world — a different show for every question', icon: 'tv', aiOnly: true },
    { id: 'strangerthings', name: 'Stranger Things', category: 'series', code: 'ST', tagline: 'Hawkins, the Upside Down and Eleven.', topic: 'the Netflix series Stranger Things', icon: 'tv', aiOnly: true },
    { id: 'got', name: 'Game of Thrones', category: 'series', code: 'GOT', tagline: 'Westeros, the Starks, the Lannisters and the Iron Throne.', topic: 'the HBO TV series Game of Thrones (2011–2019, seasons 1 to 8): its characters, houses, actors, places and big moments. Only this series, never House of the Dragon or other spin-offs', icon: 'crown',
      focus: ['seasons 1 and 2', 'seasons 3 and 4', 'seasons 5 and 6', 'seasons 7 and 8', 'House Stark', 'House Lannister', 'Daenerys Targaryen and her dragons', 'Jon Snow, the Night’s Watch and the White Walkers', 'the Greyjoys, Tyrells, Martells and Boltons', 'the actors and behind the scenes', 'places across Westeros and Essos', 'swords, sigils, house words and famous quotes'],
      offTopic: ['house of the dragon', 'rhaenyra', 'alicent', 'aemond', 'daemon', 'corlys', 'criston cole', 'dance of the dragons', 'laenor', 'laena', 'syrax', 'caraxes', 'meleys', 'vhagar', 'sunfyre', 'otto hightower', 'viserys i', 'aegon ii', 'jacaerys', 'lucerys', 'helaena', 'larys', 'mysaria', 'harwin strong', 'lyonel strong', 'vaemond', 'driftmark', 'rook’s rest', 'blood and cheese', 'dreamfyre', 'vermithor', 'silverwing', 'seasmoke', 'vermax', 'arrax', 'tessarion', 'tyraxes'] },
    { id: 'hotd', name: 'House of the Dragon', category: 'series', code: 'HOTD', tagline: 'Targaryens, dragons and the Dance of the Dragons.', topic: 'the HBO TV series House of the Dragon (2022 onwards): the Targaryen civil war called the Dance of the Dragons, its characters, dragons and riders, actors and big moments. Only this series, never Game of Thrones', icon: 'dragon',
      focus: ['the Greens: Alicent, Otto Hightower, Aegon II, Aemond and Criston Cole', 'the Blacks: Rhaenyra, Daemon and Rhaenyra’s sons', 'dragons and their riders', 'House Velaryon: Corlys, Rhaenys and their family', 'King Viserys I and the fight over who inherits the throne', 'battles and turning points of the Dance of the Dragons', 'the actors and behind the scenes', 'castles, places and the Targaryen history mentioned in the show'],
      offTopic: ['game of thrones', 'jon snow', 'daenerys', 'khaleesi', 'tyrion', 'cersei', 'jaime', 'arya', 'sansa', 'bran stark', 'ned stark', 'eddard', 'robb stark', 'joffrey', 'night king', 'white walker', 'white walkers', 'drogon', 'rhaegal', 'viserion', 'littlefinger', 'petyr baelish', 'red wedding', 'davos', 'onion knight', 'grey worm', 'unsullied', 'missandei', 'jorah', 'sandor', 'gregor clegane', 'brienne', 'podrick', 'theon', 'yara', 'euron', 'varys', 'bronn', 'gendry', 'stannis', 'renly', 'tywin', 'margaery', 'olenna', 'oberyn', 'ramsay', 'hodor', 'samwell', 'tormund', 'melisandre', 'qyburn'] },
    { id: 'breakingbad', name: 'Breaking Bad', category: 'series', code: 'BB', tagline: 'Walter White, Jesse and Better Call Saul.', topic: 'Breaking Bad and Better Call Saul', icon: 'science', aiOnly: true },
    { id: 'moneyheist', name: 'Money Heist', category: 'series', code: 'MH', tagline: 'The Professor, the Royal Mint and Bella Ciao.', topic: 'the Spanish series Money Heist (La Casa de Papel)', icon: 'mask', aiOnly: true },
    { id: 'squidgame', name: 'Squid Game', category: 'series', code: 'SQG', tagline: 'Deadly games, players and the Front Man.', topic: 'the Korean series Squid Game', icon: 'shield', aiOnly: true },
    { id: 'friends', name: 'Friends', category: 'series', code: 'FRN', tagline: 'Central Perk, Ross, Rachel and the gang.', topic: 'the sitcom Friends', icon: 'users', aiOnly: true },
    { id: 'theoffice', name: 'The Office', category: 'series', code: 'OFC', tagline: 'Dunder Mifflin, Michael Scott and pranks.', topic: 'the US sitcom The Office', icon: 'tv', aiOnly: true },
    { id: 'indianseries', name: 'Indian Web Series', category: 'series', code: 'IWS', tagline: 'Panchayat, Mirzapur, Kota Factory and more.', topic: 'Indian web series such as Panchayat, Mirzapur, Kota Factory, The Family Man, Scam 1992, Sacred Games and Paatal Lok', icon: 'tv', aiOnly: true },
    { id: 'kdrama', name: 'K-Dramas', category: 'series', code: 'KD', tagline: 'Korean dramas, stars and iconic scenes.', topic: 'popular Korean dramas (K-dramas) and their stars', icon: 'star', aiOnly: true },
    { id: 'cartoons', name: 'Cartoons', category: 'series', code: 'CTN', tagline: 'Doraemon, Shinchan, Tom & Jerry and more.', topic: 'popular cartoons such as Doraemon, Shinchan, Tom and Jerry, Oggy and the Cockroaches, Ben 10, Motu Patlu and Chhota Bheem', icon: 'sparkle', aiOnly: true },
    { id: 'onepiece', name: 'One Piece', category: 'anime', code: 'OP', tagline: 'Straw Hats, Devil Fruits and the Grand Line.', topic: 'the anime and manga One Piece by Eiichiro Oda' },
    { id: 'naruto', name: 'Naruto', category: 'anime', code: 'NRT', tagline: 'Hidden Leaf ninjas and their jutsu.', topic: 'Naruto and Naruto Shippuden' },
    { id: 'dragonball', name: 'Dragon Ball', category: 'anime', code: 'DB', tagline: 'Saiyans, Dragon Balls and power levels.', topic: 'Dragon Ball, Dragon Ball Z and Dragon Ball Super', icon: 'target', aiOnly: true },
    { id: 'demonslayer', name: 'Demon Slayer', category: 'anime', code: 'DS', tagline: 'Hashira, breathing styles and demons.', topic: 'Demon Slayer: Kimetsu no Yaiba', icon: 'flame', aiOnly: true },
    { id: 'aot', name: 'Attack on Titan', category: 'anime', code: 'AOT', tagline: 'Walls, Titans and the Survey Corps.', topic: 'Attack on Titan (Shingeki no Kyojin)', icon: 'shield', aiOnly: true },
    { id: 'jjk', name: 'Jujutsu Kaisen', category: 'anime', code: 'JJK', tagline: 'Cursed energy, sorcerers and domains.', topic: 'Jujutsu Kaisen', icon: 'bolt', aiOnly: true },
    { id: 'games', name: 'Video Games', category: 'gaming', code: 'VG', tagline: 'Consoles, classics and gaming legends.', topic: 'video games: classic and modern games, consoles, studios and characters', icon: 'gamepad', aiOnly: true },
    { id: 'minecraft', name: 'Minecraft', category: 'gaming', code: 'MC', tagline: 'Creepers, Redstone and the Ender Dragon.', topic: 'the video game Minecraft', icon: 'cube', aiOnly: true },
    { id: 'gta', name: 'Grand Theft Auto', category: 'gaming', code: 'GTA', tagline: 'Los Santos, Vice City and big heists.', topic: 'the Grand Theft Auto video game series', icon: 'car', aiOnly: true },
    { id: 'fortnite', name: 'Fortnite', category: 'gaming', code: 'FN', tagline: 'Battle royale, skins and chapters.', topic: 'the video game Fortnite', icon: 'crosshair', aiOnly: true },
    { id: 'pokemon', name: 'Pokémon', category: 'gaming', code: 'PKM', tagline: 'Pokédex, gyms and legendary Pokémon.', topic: 'Pokémon games, Pokémon species and the anime', icon: 'target', aiOnly: true },
    { id: 'mario', name: 'Super Mario', category: 'gaming', code: 'SMB', tagline: 'The Mushroom Kingdom, Bowser and power-ups.', topic: 'Super Mario and other Nintendo games', icon: 'star', aiOnly: true },
    { id: 'bgmi', name: 'BGMI & PUBG', category: 'gaming', code: 'PUBG', tagline: 'Erangel, chicken dinners and loadouts.', topic: 'Battlegrounds Mobile India (BGMI) and PUBG', icon: 'crosshair', aiOnly: true },
    { id: 'freefire', name: 'Free Fire', category: 'gaming', code: 'FF', tagline: 'Bermuda, characters and pets.', topic: 'the mobile game Garena Free Fire', icon: 'flame', aiOnly: true },
    { id: 'valorant', name: 'Valorant', category: 'gaming', code: 'VAL', tagline: 'Agents, maps and abilities.', topic: 'the video game Valorant', icon: 'target', aiOnly: true },
    { id: 'cod', name: 'Call of Duty', category: 'gaming', code: 'COD', tagline: 'Campaigns, Warzone and legendary maps.', topic: 'the Call of Duty video game series, including Warzone and Call of Duty Mobile', icon: 'crosshair', aiOnly: true },
    { id: 'clash', name: 'Clash of Clans & Royale', category: 'gaming', code: 'COC', tagline: 'Troops, towers and Supercell battles.', topic: 'Clash of Clans, Clash Royale and other Supercell games', icon: 'shield', aiOnly: true },
    { id: 'zelda', name: 'The Legend of Zelda', category: 'gaming', code: 'LOZ', tagline: 'Link, Hyrule and the Master Sword.', topic: 'The Legend of Zelda video game series', icon: 'shield', aiOnly: true },
    { id: 'cricket', name: 'Cricket', category: 'sports', code: 'CRK', tagline: 'World Cups, legends and the laws of the game.', topic: 'cricket: IPL, World Cups, legends and the laws of the game' },
    { id: 'football', name: 'Football', category: 'sports', code: 'FTB', tagline: 'World Cups, clubs and superstars.', topic: 'football (soccer): World Cups, clubs, players and rules' },
    { id: 'f1', name: 'Formula 1', category: 'sports', code: 'F1', tagline: 'Drivers, teams and legendary circuits.', topic: 'Formula 1 motor racing', icon: 'flag', aiOnly: true },
    { id: 'basketball', name: 'Basketball', category: 'sports', code: 'BSK', tagline: 'NBA legends, records and big moments.', topic: 'basketball and the NBA', icon: 'ball', aiOnly: true },
    { id: 'surprise', name: 'Surprise Me', category: 'party', code: 'MIX', tagline: 'Every question on a different random topic.', topic: 'a surprise mix of trivia — every question on a different topic: pop culture, science, sports, geography, food, history, anime, music and technology', icon: 'dice', aiOnly: true },
    { id: 'gk', name: 'General Knowledge', category: 'party', code: 'GK', tagline: 'A bit of everything, pub-quiz style.', topic: 'general knowledge', icon: 'bulb', aiOnly: true },
    { id: 'music', name: 'Music', category: 'party', code: 'MUS', tagline: 'Artists, songs and instruments.', topic: 'music: artists, songs, albums and instruments, including Indian film music', icon: 'music', aiOnly: true },
    { id: 'custom', name: 'Any topic', category: 'party', code: 'AI', tagline: 'Anything you type.', topic: '', icon: 'sparkle', aiOnly: true, hidden: true },
  ];

  // MCQ answers are the index into `options`; options are shuffled per game at runtime.
  // Written answers are compared against `accept` (case, spacing and punctuation are ignored).
  const QUESTION_BANK = {
    web: [
      { type: 'mcq', q: 'Which HTML element defines the most important (top-level) heading on a page?', options: ['<h1>', '<heading>', '<h6>', '<head>'], answer: 0, mono: true, explain: '<h1> is the top-level heading and <h6> the least important. <head> holds page metadata, not visible headings.' },
      { type: 'mcq', q: 'Which CSS property controls the space between an element’s content and its border?', options: ['padding', 'margin', 'spacing', 'border-gap'], answer: 0, mono: true, explain: 'Padding sits inside the border; margin sits outside it.' },
      { type: 'mcq', q: 'In a default flex row, what does this rule do to the children of .toolbar?', code: '.toolbar {\n  display: flex;\n  justify-content: center;\n}', lang: 'css', options: ['Centers them horizontally along the main axis', 'Centers them vertically', 'Wraps them onto new lines', 'Stretches them to fill the width'], answer: 0, explain: 'justify-content aligns items along the main axis, which is horizontal for flex-direction: row.' },
      { type: 'mcq', q: 'Which attribute fills the blank so screen readers can describe this image?', code: '<img src="logo.png" ____="QuizNova logo">', lang: 'html', options: ['alt', 'title', 'label', 'desc'], answer: 0, mono: true, explain: 'The alt attribute provides alternative text for assistive technology and for when the image fails to load.' },
      { type: 'mcq', q: 'Which selector has the highest specificity?', options: ['#menu', '.menu li a', 'ul li a', 'nav > a'], answer: 0, mono: true, explain: 'An ID selector (1,0,0) outranks any number of class and element selectors.' },
      { type: 'written', q: 'Which CSS property changes the text colour of an element?', accept: ['color', 'colour'], answerText: 'color', explain: 'The color property sets the foreground (text) colour.' },
      { type: 'mcq', q: 'Which HTML5 element is meant for a block of major navigation links?', options: ['<nav>', '<menu>', '<links>', '<navigation>'], answer: 0, mono: true, explain: '<nav> is the semantic sectioning element for major navigation blocks.' },
      { type: 'mcq', q: 'Given this rule, how wide is the left margin of each paragraph?', code: 'p {\n  margin: 10px 20px;\n}', lang: 'css', options: ['20px', '10px', '0', '30px'], answer: 0, mono: true, explain: 'With two values, the first sets top and bottom, the second sets left and right.' },
      { type: 'written', q: 'What does the abbreviation CSS stand for?', accept: ['cascading style sheets', 'cascading style sheet', 'cascading stylesheets', 'cascading stylesheet'], answerText: 'Cascading Style Sheets', explain: '“Cascading” refers to how rules from several sources combine and override each other.' },
      { type: 'mcq', q: 'Which CSS unit is relative to the root element’s font size?', options: ['rem', 'em', 'vh', 'px'], answer: 0, mono: true, explain: 'rem means “root em”. A plain em is relative to the element’s own font size.' },
    ],
    js: [
      { type: 'mcq', q: 'What does this code print?', code: 'console.log(typeof null);', lang: 'js', options: ['"object"', '"null"', '"undefined"', '"number"'], answer: 0, mono: true, explain: 'A long-standing quirk of the language: typeof null returns "object".' },
      { type: 'mcq', q: 'Which keyword declares a block-scoped variable that cannot be reassigned?', options: ['const', 'let', 'var', 'static'], answer: 0, mono: true, explain: 'const is block-scoped and cannot be reassigned, although an object it holds can still be mutated.' },
      { type: 'mcq', q: 'What is logged to the console?', code: 'const nums = [1, 2, 3];\nconsole.log(nums.map(n => n * 2));', lang: 'js', options: ['[2, 4, 6]', '[1, 2, 3]', '12', '[1, 4, 9]'], answer: 0, mono: true, explain: 'map returns a new array with the callback applied to every element.' },
      { type: 'mcq', q: 'What does this comparison evaluate to?', code: '0.1 + 0.2 === 0.3', lang: 'js', options: ['false', 'true', 'undefined', 'It throws a TypeError'], answer: 0, explain: 'Floating-point rounding makes 0.1 + 0.2 equal 0.30000000000000004.' },
      { type: 'written', q: 'Which array method returns a new array containing only the elements that pass a test?', accept: ['filter', 'filter()', '.filter', '.filter()', 'array.filter', 'array.filter()', 'array.prototype.filter', 'array.prototype.filter()'], answerText: 'filter()', explain: 'filter keeps every element for which the callback returns a truthy value.' },
      { type: 'mcq', q: 'Which method turns a JSON string into a JavaScript object?', options: ['JSON.parse()', 'JSON.stringify()', 'JSON.toObject()', 'Object.fromJSON()'], answer: 0, mono: true, explain: 'JSON.parse reads JSON text; JSON.stringify does the reverse.' },
      { type: 'mcq', q: 'What does this code print?', code: 'let a = "5";\nlet b = 2;\nconsole.log(a * b, a + b);', lang: 'js', options: ['10 52', '52 7', '10 7', 'NaN 52'], answer: 0, mono: true, explain: '* converts "5" to a number (10), but + with a string concatenates ("52").' },
      { type: 'mcq', q: 'What does the strict equality operator === compare?', options: ['Both value and type', 'Only the value', 'Only the memory address', 'Only the type'], answer: 0, explain: '=== never coerces types, so 1 === "1" is false.' },
      { type: 'written', q: 'Which DOM method attaches an event handler, such as a "click" handler, to an element?', accept: ['addeventlistener', 'addeventlistener()', '.addeventlistener', '.addeventlistener()', 'element.addeventlistener', 'element.addeventlistener()'], answerText: 'addEventListener()', explain: 'element.addEventListener("click", handler) registers a listener without overwriting existing ones.' },
      { type: 'mcq', q: 'In what order are the letters logged?', code: 'setTimeout(() => console.log("A"), 0);\nconsole.log("B");', lang: 'js', options: ['B, then A', 'A, then B', 'Only A', 'Only B'], answer: 0, explain: 'The timeout callback is queued and runs after the current script finishes, even with a 0 ms delay.' },
    ],
    devops: [
      { type: 'mcq', q: 'Which command creates a new, empty Git repository in the current folder?', options: ['git init', 'git start', 'git create', 'git new'], answer: 0, mono: true, explain: 'git init creates the hidden .git directory that stores the project history.' },
      { type: 'mcq', q: 'What does git clone do?', options: ['Copies a remote repository, including its history, to your machine', 'Creates a new branch', 'Uploads your commits to GitHub', 'Deletes untracked files'], answer: 0, explain: 'git clone downloads the full repository and sets it up as the “origin” remote.' },
      { type: 'mcq', q: 'Which file defines a Jenkins pipeline as code inside a repository?', options: ['Jenkinsfile', 'pipeline.yml', 'jenkins.json', 'build.xml'], answer: 0, mono: true, explain: 'A Jenkinsfile committed to the repo lets Jenkins build the pipeline straight from source control.' },
      { type: 'mcq', q: 'In DevOps, what does CI stand for?', options: ['Continuous Integration', 'Code Inspection', 'Container Instance', 'Central Infrastructure'], answer: 0, explain: 'Continuous Integration merges and tests changes frequently, usually on every push.' },
      { type: 'written', q: 'Which Git command uploads your local commits to a remote repository?', accept: ['git push', 'push', 'git push origin', 'git push origin main'], answerText: 'git push', explain: 'git push sends commits from your local branch to its remote branch.' },
      { type: 'mcq', q: 'Which command shows staged, unstaged and untracked changes?', options: ['git status', 'git log', 'git show', 'git remote'], answer: 0, mono: true, explain: 'git status summarises the working tree and the staging area.' },
      { type: 'mcq', q: 'What is GitHub Pages used for?', options: ['Hosting static websites directly from a repository', 'Running Jenkins build agents', 'Storing Docker images', 'Tracking time spent on issues'], answer: 0, explain: 'GitHub Pages serves HTML, CSS and JavaScript straight from a branch — a good fit for this quiz app.' },
      { type: 'mcq', q: 'In this Jenkinsfile, what does agent any mean?', code: "pipeline {\n  agent any\n  stages {\n    stage('Build') {\n      steps { echo 'Building...' }\n    }\n  }\n}", lang: 'groovy', options: ['Run the pipeline on any available agent', 'Run only on the Jenkins controller', 'Skip the build stage', 'Run inside a Docker container'], answer: 0, explain: 'agent any lets Jenkins schedule the pipeline on whichever executor is free.' },
      { type: 'written', q: 'Which Git command combines another branch’s history into your current branch?', accept: ['git merge', 'merge'], answerText: 'git merge', explain: 'git merge <branch> integrates that branch into the one you have checked out.' },
      { type: 'mcq', q: 'What is a pull request on GitHub?', options: ['A proposal to merge changes that others can review first', 'A command that downloads a repository', 'A way to delete a remote branch', 'An automatic rollback of the last commit'], answer: 0, explain: 'Pull requests collect review, discussion and CI results before changes are merged.' },
    ],
    dsa: [
      { type: 'mcq', q: 'Which data structure follows Last-In, First-Out (LIFO) order?', options: ['Stack', 'Queue', 'Linked list', 'Binary tree'], answer: 0, explain: 'The last item pushed onto a stack is the first one popped off.' },
      { type: 'mcq', q: 'What is the in-order traversal of this binary search tree?', image: 'bst', caption: 'Binary search tree', options: ['1, 3, 6, 8, 10, 14', '8, 3, 1, 6, 10, 14', '1, 6, 3, 14, 10, 8', '8, 10, 14, 3, 6, 1'], answer: 0, mono: true, explain: 'In-order visits the left subtree, the node, then the right subtree, which always yields sorted order in a BST.' },
      { type: 'mcq', q: 'What is the time complexity of binary search on a sorted array?', options: ['O(log n)', 'O(n)', 'O(1)', 'O(n log n)'], answer: 0, mono: true, explain: 'Each comparison halves the remaining search space.' },
      { type: 'mcq', q: 'Breadth-first search (BFS) is usually implemented with which structure?', options: ['Queue', 'Stack', 'Heap', 'Hash map'], answer: 0, explain: 'A first-in, first-out queue makes BFS explore the graph level by level.' },
      { type: 'written', q: 'In Big-O notation, what is the time complexity of reading an array element by its index?', accept: ['o(1)', 'o1', 'constant', 'constant time'], answerText: 'O(1)', explain: 'Arrays compute an element’s address directly, so access takes constant time.' },
      { type: 'mcq', q: 'What is the average-case lookup time in a well-distributed hash table?', options: ['O(1)', 'O(log n)', 'O(n)', 'O(n²)'], answer: 0, mono: true, explain: 'Hashing jumps straight to a bucket; collisions only matter in the worst case.' },
      { type: 'mcq', q: 'In which linked list does every node point to both the next and the previous node?', options: ['Doubly linked list', 'Singly linked list', 'Circular singly linked list', 'Skip list'], answer: 0, explain: 'Doubly linked nodes hold both prev and next pointers, so you can walk the list in either direction.' },
      { type: 'mcq', q: 'What does this code log?', code: 'const stack = [];\nstack.push(1);\nstack.push(2);\nstack.push(3);\nstack.pop();\nconsole.log(stack);', lang: 'js', options: ['[1, 2]', '[2, 3]', '[1, 2, 3]', '[3]'], answer: 0, mono: true, explain: 'pop removes the most recently pushed item, which is 3.' },
      { type: 'written', q: 'How many edges does a tree with 10 nodes have?', accept: ['9', 'nine'], answerText: '9', explain: 'A tree with n nodes always has exactly n − 1 edges.' },
      { type: 'mcq', q: 'Which sorting algorithm guarantees O(n log n) time even in the worst case?', options: ['Merge sort', 'Quick sort', 'Bubble sort', 'Insertion sort'], answer: 0, explain: 'Merge sort always splits evenly; quick sort degrades to O(n²) with bad pivots.' },
    ],
    science: [
      { type: 'mcq', q: 'What is the chemical symbol for gold?', options: ['Au', 'Ag', 'Gd', 'Go'], answer: 0, explain: 'Au comes from the Latin word aurum. Ag is silver.' },
      { type: 'mcq', q: 'Which organelle is known as the powerhouse of the cell?', options: ['Mitochondria', 'Nucleus', 'Ribosome', 'Golgi apparatus'], answer: 0, explain: 'Mitochondria produce most of the cell’s ATP through respiration.' },
      { type: 'mcq', q: 'Approximately how fast does light travel in a vacuum?', options: ['3 × 10⁸ m/s', '3 × 10⁶ m/s', '3 × 10⁵ m/s', '3 × 10¹⁰ m/s'], answer: 0, explain: 'Light travels about 299,792 km every second — roughly 3 × 10⁸ metres per second.' },
      { type: 'mcq', q: 'Which planet is known as the Red Planet?', options: ['Mars', 'Venus', 'Jupiter', 'Mercury'], answer: 0, explain: 'Iron oxide (rust) in its surface dust gives Mars its reddish colour.' },
      { type: 'written', q: 'Which gas do plants absorb from the air for photosynthesis?', accept: ['carbon dioxide', 'co2', 'co₂', 'carbon-dioxide'], answerText: 'Carbon dioxide (CO₂)', explain: 'Plants combine CO₂, water and light energy to make glucose, releasing oxygen.' },
      { type: 'mcq', q: 'What is the SI unit of force?', options: ['Newton', 'Joule', 'Watt', 'Pascal'], answer: 0, explain: 'One newton accelerates 1 kg at 1 m/s². Joule is energy, watt is power and pascal is pressure.' },
      { type: 'mcq', q: 'Which subatomic particle carries a negative charge?', options: ['Electron', 'Proton', 'Neutron', 'Photon'], answer: 0, explain: 'Electrons are negative, protons are positive and neutrons are neutral.' },
      { type: 'mcq', q: 'What is the pH of pure water at 25 °C?', options: ['7', '0', '14', '1'], answer: 0, explain: 'Pure water is neutral, which is pH 7 at 25 °C.' },
      { type: 'written', q: 'What is the chemical formula of water?', accept: ['h2o', 'h₂o'], answerText: 'H₂O', explain: 'Each water molecule has two hydrogen atoms bonded to one oxygen atom.' },
      { type: 'mcq', q: 'Which organ produces insulin?', options: ['Pancreas', 'Liver', 'Kidney', 'Stomach'], answer: 0, explain: 'Beta cells in the pancreas release insulin to regulate blood sugar.' },
    ],
    math: [
      { type: 'mcq', q: 'Find the length of the hypotenuse x.', image: 'triangle', caption: 'Right triangle with legs 6 and 8', options: ['10', '12', '14', '9.8'], answer: 0, explain: 'By Pythagoras, x² = 6² + 8² = 100, so x = 10.' },
      { type: 'mcq', q: 'What is π rounded to two decimal places?', options: ['3.14', '3.41', '3.12', '3.16'], answer: 0, explain: 'π ≈ 3.14159…' },
      { type: 'mcq', q: 'What is the derivative of x² with respect to x?', options: ['2x', 'x', 'x³ / 3', '2'], answer: 0, explain: 'Power rule: the derivative of xⁿ is n·xⁿ⁻¹.' },
      { type: 'written', q: 'What is 15% of 200?', accept: ['30', '30.0'], answerText: '30', explain: '0.15 × 200 = 30.' },
      { type: 'mcq', q: 'What is the sum of the interior angles of a hexagon?', options: ['720°', '540°', '360°', '1080°'], answer: 0, explain: '(n − 2) × 180° = 4 × 180° = 720°.' },
      { type: 'mcq', q: 'Solve for x:  3x + 5 = 20', options: ['5', '15', '25', '3'], answer: 0, explain: '3x = 15, so x = 5.' },
      { type: 'mcq', q: 'Which of these numbers is prime?', options: ['29', '21', '27', '33'], answer: 0, explain: '29 has no divisors other than 1 and itself; 21 = 3·7, 27 = 3³ and 33 = 3·11.' },
      { type: 'written', q: 'What is the square root of 144?', accept: ['12', 'twelve', '+12', '±12'], answerText: '12', explain: '12 × 12 = 144.' },
      { type: 'mcq', q: 'What is log₁₀(1000)?', options: ['3', '10', '100', '30'], answer: 0, explain: '10³ = 1000.' },
      { type: 'mcq', q: 'What is the probability of getting heads when flipping a fair coin?', options: ['1/2', '1/3', '1/4', '1'], answer: 0, explain: 'There are two equally likely outcomes and one of them is heads.' },
    ],
    marvel: [
      { type: 'mcq', q: 'What is the name of Thor’s enchanted hammer?', options: ['Mjolnir', 'Stormbreaker', 'Gungnir', 'Jarnbjorn'], answer: 0, explain: 'Mjolnir is Thor’s hammer. Stormbreaker is the axe he forges in Avengers: Infinity War.' },
      { type: 'mcq', q: 'In the MCU, Captain America’s shield is made mainly of which metal?', options: ['Vibranium', 'Adamantium', 'Uru', 'Carbonadium'], answer: 0, explain: 'Howard Stark built the shield from Wakandan vibranium.' },
      { type: 'mcq', q: 'What is Tony Stark’s AI assistant called in the early Iron Man films?', options: ['J.A.R.V.I.S.', 'F.R.I.D.A.Y.', 'E.D.I.T.H.', 'KAREN'], answer: 0, explain: 'J.A.R.V.I.S. runs Tony’s suits until it becomes Vision; F.R.I.D.A.Y. takes over later.' },
      { type: 'mcq', q: 'On which planet was the Soul Stone hidden?', options: ['Vormir', 'Xandar', 'Titan', 'Sakaar'], answer: 0, explain: 'The Red Skull guards the Soul Stone on Vormir, where it demands a sacrifice.' },
      { type: 'written', q: 'What is the first name of Peter Parker’s aunt, who raises him?', accept: ['may', 'aunt may', 'may parker'], answerText: 'May', explain: 'Aunt May raises Peter in Queens after his parents are gone.' },
      { type: 'mcq', q: 'Which fictional African nation is ruled by Black Panther?', options: ['Wakanda', 'Genosha', 'Latveria', 'Sokovia'], answer: 0, explain: 'Wakanda hides its vibranium-powered technology from the world.' },
      { type: 'mcq', q: 'Which actor played Tony Stark in the Marvel Cinematic Universe?', options: ['Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'], answer: 0, explain: 'Robert Downey Jr. played Tony Stark from Iron Man (2008) to Avengers: Endgame (2019).' },
      { type: 'mcq', q: 'Which Guardian of the Galaxy is a tree-like being who only says “I am Groot”?', options: ['Groot', 'Rocket', 'Drax', 'Mantis'], answer: 0, explain: 'Groot is a Flora colossus whose only words are “I am Groot”.' },
      { type: 'written', q: 'What is the real name of the Hulk?', accept: ['bruce banner', 'banner', 'robert bruce banner', 'dr bruce banner', 'doctor bruce banner'], answerText: 'Bruce Banner', explain: 'Dr. Bruce Banner turns into the Hulk after exposure to gamma radiation.' },
      { type: 'mcq', q: 'Which film kicked off the Marvel Cinematic Universe in 2008?', options: ['Iron Man', 'The Incredible Hulk', 'Thor', 'Captain America: The First Avenger'], answer: 0, explain: 'Iron Man opened in May 2008; The Incredible Hulk followed a month later.' },
    ],
    dc: [
      { type: 'mcq', q: 'What is Superman’s home planet?', options: ['Krypton', 'Apokolips', 'Thanagar', 'Oa'], answer: 0, explain: 'Baby Kal-El was sent to Earth just before Krypton exploded.' },
      { type: 'mcq', q: 'Which city does Batman protect?', options: ['Gotham City', 'Metropolis', 'Central City', 'Star City'], answer: 0, explain: 'Gotham is Batman’s city; Metropolis belongs to Superman.' },
      { type: 'mcq', q: 'What is the Flash’s main superpower?', options: ['Super speed', 'Flight', 'Invisibility', 'Telepathy'], answer: 0, explain: 'The Flash draws on the Speed Force to move faster than light.' },
      { type: 'mcq', q: 'What is the name of Wonder Woman’s home island?', options: ['Themyscira', 'Atlantis', 'Krypton', 'Apokolips'], answer: 0, explain: 'Diana grew up among the Amazons on the hidden island of Themyscira.' },
      { type: 'written', q: 'What is Batman’s secret identity?', accept: ['bruce wayne', 'wayne'], answerText: 'Bruce Wayne', explain: 'Billionaire Bruce Wayne became Batman after his parents were murdered.' },
      { type: 'mcq', q: 'Who is Batman’s loyal butler?', options: ['Alfred Pennyworth', 'Lucius Fox', 'James Gordon', 'Dick Grayson'], answer: 0, explain: 'Alfred raised Bruce and helps run the Batcave.' },
      { type: 'mcq', q: 'Which substance weakens Superman?', options: ['Kryptonite', 'Vibranium', 'Adamantium', 'Nth metal'], answer: 0, explain: 'Radioactive fragments of Krypton — kryptonite — drain Superman’s powers.' },
      { type: 'mcq', q: 'Where does a Green Lantern’s power come from?', options: ['A power ring', 'A magic lasso', 'A cosmic belt', 'A mystic amulet'], answer: 0, explain: 'The power ring turns willpower into hard-light constructs.' },
      { type: 'mcq', q: 'Which villain is known as the “Clown Prince of Crime”?', options: ['The Joker', 'The Riddler', 'The Penguin', 'Two-Face'], answer: 0, explain: 'The Joker is Batman’s most famous arch-enemy.' },
      { type: 'written', q: 'At which newspaper does Clark Kent work as a reporter?', accept: ['daily planet', 'the daily planet'], answerText: 'The Daily Planet', explain: 'Clark works at the Daily Planet in Metropolis alongside Lois Lane.' },
    ],
    hollywood: [
      { type: 'mcq', q: 'Who directed both Titanic (1997) and Avatar (2009)?', options: ['James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'], answer: 0, explain: 'James Cameron directed both, and both became the highest-grossing film of their time.' },
      { type: 'mcq', q: 'In The Lion King (1994), what is the name of Simba’s father?', options: ['Mufasa', 'Scar', 'Rafiki', 'Zazu'], answer: 0, explain: 'Mufasa is king of the Pride Lands; Scar is his jealous brother.' },
      { type: 'mcq', q: 'Which film series made the line “May the Force be with you” famous?', options: ['Star Wars', 'Star Trek', 'Dune', 'Guardians of the Galaxy'], answer: 0, explain: 'The line has been part of Star Wars since the first film in 1977.' },
      { type: 'mcq', q: 'Which of these films did Christopher Nolan direct?', options: ['Inception', 'Avatar', 'Jurassic Park', 'The Matrix'], answer: 0, explain: 'Nolan directed Inception (2010); The Matrix was made by the Wachowskis.' },
      { type: 'written', q: 'In Toy Story, what is the name of the cowboy toy?', accept: ['woody', 'sheriff woody'], answerText: 'Woody', explain: 'Sheriff Woody is Andy’s favourite toy until Buzz Lightyear arrives.' },
      { type: 'mcq', q: 'Which film is set on the fictional island of Isla Nublar?', options: ['Jurassic Park', 'King Kong', 'Jaws', 'Pirates of the Caribbean'], answer: 0, explain: 'John Hammond builds his dinosaur park on Isla Nublar.' },
      { type: 'mcq', q: 'Who plays Captain Jack Sparrow in Pirates of the Caribbean?', options: ['Johnny Depp', 'Orlando Bloom', 'Brad Pitt', 'Keanu Reeves'], answer: 0, explain: 'Johnny Depp was Oscar-nominated for the role in The Curse of the Black Pearl.' },
      { type: 'mcq', q: 'In The Matrix, which pill does Neo take?', options: ['The red pill', 'The blue pill', 'The green pill', 'The yellow pill'], answer: 0, explain: 'The red pill shows Neo the truth about the Matrix.' },
      { type: 'mcq', q: 'Which animated film features Elsa, a queen with ice powers?', options: ['Frozen', 'Tangled', 'Moana', 'Brave'], answer: 0, explain: 'Frozen (2013) follows Elsa and her sister Anna in Arendelle.' },
      { type: 'written', q: 'What is the name of the wizarding school in Harry Potter?', accept: ['hogwarts', 'hogwarts school', 'hogwarts school of witchcraft and wizardry'], answerText: 'Hogwarts', explain: 'Hogwarts School of Witchcraft and Wizardry is where Harry studies magic.' },
    ],
    mcu: [
      { type: 'mcq', q: 'Which Infinity Stone is hidden inside the Tesseract?', options: ['The Space Stone', 'The Mind Stone', 'The Reality Stone', 'The Time Stone'], answer: 0, explain: 'The Tesseract houses the Space Stone, which Loki uses to open a portal over New York in The Avengers (2012).' },
      { type: 'mcq', q: 'In which film did Tom Holland’s Spider-Man first appear in the MCU?', options: ['Captain America: Civil War', 'Spider-Man: Homecoming', 'Avengers: Infinity War', 'Avengers: Age of Ultron'], answer: 0, explain: 'Peter Parker debuted in Captain America: Civil War (2016), before his own film Spider-Man: Homecoming (2017).' },
      { type: 'mcq', q: 'Which directing duo made Captain America: The Winter Soldier, Civil War, Avengers: Infinity War and Endgame?', options: ['The Russo brothers', 'The Wachowskis', 'The Coen brothers', 'The Duffer brothers'], answer: 0, explain: 'Anthony and Joe Russo directed all four films.' },
      { type: 'mcq', q: 'In which film does Thanos first appear, in a mid-credits scene?', options: ['The Avengers (2012)', 'Guardians of the Galaxy', 'Avengers: Age of Ultron', 'Iron Man 3'], answer: 0, explain: 'Thanos turns and smiles at the end of The Avengers (2012), years before Infinity War.' },
      { type: 'mcq', q: 'Which MCU film was the first superhero movie nominated for the Oscar for Best Picture?', options: ['Black Panther', 'Avengers: Endgame', 'Iron Man', 'Guardians of the Galaxy'], answer: 0, explain: 'Black Panther (2018) earned seven Oscar nominations, including Best Picture, and won three.' },
      { type: 'mcq', q: 'Which actor plays Hela, the goddess of death, in Thor: Ragnarok?', options: ['Cate Blanchett', 'Tilda Swinton', 'Natalie Portman', 'Tessa Thompson'], answer: 0, explain: 'Cate Blanchett plays Hela, Odin’s firstborn child, in Thor: Ragnarok (2017).' },
      { type: 'mcq', q: 'What is the name of the elite all-female special forces unit that guards Wakanda’s royal family?', options: ['The Dora Milaje', 'The Ravagers', 'The Ten Rings', 'The Kree Starforce'], answer: 0, explain: 'The Dora Milaje, led by Okoye, are Wakanda’s royal guard.' },
      { type: 'mcq', q: 'Which of these heroes was NOT on the Avengers team in The Avengers (2012)?', options: ['Falcon', 'Hawkeye', 'Black Widow', 'Hulk'], answer: 0, explain: 'The 2012 team was Iron Man, Captain America, Thor, Hulk, Black Widow and Hawkeye. Falcon debuted in Captain America: The Winter Soldier (2014).' },
      { type: 'written', q: 'What is the title of the 2021 Disney+ series in which Wanda Maximoff’s life plays out like classic TV sitcoms?', accept: ['wandavision', 'wanda vision'], answerText: 'WandaVision', explain: 'WandaVision (2021) starred Elizabeth Olsen and Paul Bettany and was the first MCU series on Disney+.' },
      { type: 'written', q: 'In Avengers: Endgame, Tony Stark and his daughter Morgan share the line “I love you ___”. Which number completes it?', accept: ['3000', 'three thousand', 'i love you 3000'], answerText: '3000', explain: '“I love you 3000” is the father-daughter line in Avengers: Endgame (2019).' },
    ],
    indian: [
      { type: 'mcq', q: 'The song “Naatu Naatu” won the Oscar for Best Original Song. Which film is it from?', options: ['RRR', 'Baahubali 2', 'Pushpa', 'KGF'], answer: 0, explain: 'Naatu Naatu from the Telugu film RRR won the Academy Award in 2023.' },
      { type: 'mcq', q: 'Who directed Baahubali and RRR?', options: ['S. S. Rajamouli', 'Mani Ratnam', 'Sukumar', 'Prashanth Neel'], answer: 0, explain: 'S. S. Rajamouli directed both epics.' },
      { type: 'mcq', q: 'What is the name of the famous villain in Sholay (1975)?', options: ['Gabbar Singh', 'Mogambo', 'Shakaal', 'Kancha Cheena'], answer: 0, explain: 'Amjad Khan’s Gabbar Singh is one of Hindi cinema’s most famous villains.' },
      { type: 'mcq', q: 'Which 2009 film follows the friends Rancho, Farhan and Raju?', options: ['3 Idiots', 'Zindagi Na Milegi Dobara', 'Dil Chahta Hai', 'Munna Bhai M.B.B.S.'], answer: 0, explain: '3 Idiots, starring Aamir Khan, is set in an engineering college.' },
      { type: 'written', q: 'In Baahubali, who killed Amarendra Baahubali?', accept: ['kattappa', 'katappa'], answerText: 'Kattappa', explain: '“Why did Kattappa kill Baahubali?” was the cliffhanger answered in Baahubali 2.' },
      { type: 'mcq', q: 'Which film about a village cricket match was nominated for the Oscar for Best Foreign Language Film in 2002?', options: ['Lagaan', 'Chak De! India', 'Iqbal', '83'], answer: 0, explain: 'Lagaan (2001) was nominated at the 74th Academy Awards.' },
      { type: 'mcq', q: 'Dangal (2016) is about which sport?', options: ['Wrestling', 'Boxing', 'Kabaddi', 'Hockey'], answer: 0, explain: 'Dangal tells the story of wrestler Mahavir Singh Phogat and his daughters.' },
      { type: 'mcq', q: 'Which actor do fans call “Thalaivar”?', options: ['Rajinikanth', 'Kamal Haasan', 'Chiranjeevi', 'Mohanlal'], answer: 0, explain: 'Thalaivar means “leader”, and it is the nickname fans use for Rajinikanth.' },
      { type: 'mcq', q: 'Who plays Pushpa Raj in Pushpa: The Rise?', options: ['Allu Arjun', 'Ram Charan', 'Jr. NTR', 'Prabhas'], answer: 0, explain: 'Allu Arjun won the National Film Award for Best Actor for the role.' },
      { type: 'written', q: 'In which city is the Hindi film industry, “Bollywood”, based?', accept: ['mumbai', 'bombay'], answerText: 'Mumbai', explain: 'The name Bollywood blends Bombay (now Mumbai) and Hollywood.' },
    ],
    tfi: [
      { type: 'mcq', q: 'Which actor plays Komaram Bheem in RRR (2022)?', options: ['Jr. NTR', 'Ram Charan', 'Allu Arjun', 'Mahesh Babu'], answer: 0, explain: 'Jr. NTR plays the tribal hero Komaram Bheem, and Ram Charan plays Alluri Sitarama Raju.' },
      { type: 'mcq', q: 'Who directed Pushpa: The Rise (2021) and Pushpa 2: The Rule (2024)?', options: ['Sukumar', 'Trivikram Srinivas', 'Koratala Siva', 'Boyapati Srinu'], answer: 0, explain: 'Sukumar directed both Pushpa films, starring Allu Arjun.' },
      { type: 'written', q: 'Which hero played the title role in Baahubali: The Beginning (2015) and Baahubali 2 (2017)?', accept: ['prabhas', 'darling prabhas', 'rebel star prabhas'], answerText: 'Prabhas', explain: 'Prabhas played Baahubali, while Rana Daggubati played his rival Bhallaladeva.' },
      { type: 'mcq', q: 'Which director made Arjun Reddy (2017), later remade in Hindi as Kabir Singh?', options: ['Sandeep Reddy Vanga', 'Puri Jagannadh', 'Harish Shankar', 'Sekhar Kammula'], answer: 0, explain: 'Sandeep Reddy Vanga directed Arjun Reddy and its Hindi remake, Kabir Singh (2019).' },
      { type: 'mcq', q: 'Who directed the 2024 sci-fi epic Kalki 2898 AD, starring Prabhas?', options: ['Nag Ashwin', 'Prashanth Neel', 'Atlee', 'Sandeep Reddy Vanga'], answer: 0, explain: 'Nag Ashwin directed Kalki 2898 AD, which also stars Amitabh Bachchan, Kamal Haasan and Deepika Padukone.' },
      { type: 'written', q: 'Which hero starred in both Pokiri (2006) and Sarileru Neekevvaru (2020)?', accept: ['mahesh babu', 'mahesh', 'superstar mahesh babu', 'superstar mahesh', 'prince mahesh babu'], answerText: 'Mahesh Babu', explain: 'Mahesh Babu led both films, directed by Puri Jagannadh and Anil Ravipudi.' },
      { type: 'mcq', q: 'Which director made Salaar: Part 1 – Ceasefire (2023), starring Prabhas?', options: ['Prashanth Neel', 'Nag Ashwin', 'Sujeeth', 'Om Raut'], answer: 0, explain: 'Prashanth Neel, who made the KGF films, directed Salaar with Prabhas as Deva.' },
      { type: 'mcq', q: 'In Sukumar’s Rangasthalam (2018), which hero plays the hard-of-hearing villager Chitti Babu?', options: ['Ram Charan', 'Allu Arjun', 'Jr. NTR', 'Nani'], answer: 0, explain: 'Ram Charan’s Chitti Babu, a partly deaf villager, is one of his most praised roles.' },
      { type: 'mcq', q: 'Which director made Athadu, Khaleja and Guntur Kaaram with Mahesh Babu?', options: ['Trivikram Srinivas', 'Koratala Siva', 'Puri Jagannadh', 'Anil Ravipudi'], answer: 0, explain: 'Trivikram Srinivas directed all three: Athadu (2005), Khaleja (2010) and Guntur Kaaram (2024).' },
      { type: 'mcq', q: 'Which hero starred in Gabbar Singh (2012), Harish Shankar’s remake of the Hindi hit Dabangg?', options: ['Pawan Kalyan', 'Ravi Teja', 'Mahesh Babu', 'Jr. NTR'], answer: 0, explain: 'Pawan Kalyan plays a police officer in Gabbar Singh, a blockbuster remake of Dabangg.' },
      { type: 'mcq', q: 'Which director made Srimanthudu (2015) and Bharat Ane Nenu (2018) with Mahesh Babu?', options: ['Koratala Siva', 'Trivikram Srinivas', 'Vamshi Paidipally', 'Sreenu Vaitla'], answer: 0, explain: 'Koratala Siva directed both films and later made Devara: Part 1 (2024) with Jr. NTR.' },
      { type: 'mcq', q: 'In which 2017 film does Jr. NTR play three brothers?', options: ['Jai Lava Kusa', 'Temper', 'Janatha Garage', 'Nannaku Prematho'], answer: 0, explain: 'In Jai Lava Kusa, Jr. NTR plays the brothers Jai, Lava and Kusa.' },
      { type: 'mcq', q: 'The chartbuster song “Butta Bomma” is from which Allu Arjun film?', options: ['Ala Vaikunthapurramuloo', 'Sarrainodu', 'Race Gurram', 'Duvvada Jagannadham'], answer: 0, explain: '“Butta Bomma”, composed by S. Thaman, is from Trivikram’s Ala Vaikunthapurramuloo (2020).' },
      { type: 'mcq', q: 'Which 2009 S. S. Rajamouli film stars Ram Charan as a warrior reborn after 400 years?', options: ['Magadheera', 'Yamadonga', 'Chatrapathi', 'Vikramarkudu'], answer: 0, explain: 'In Magadheera, Ram Charan plays the warrior Kala Bhairava and his modern-day rebirth, Harsha.' },
      { type: 'mcq', q: 'Who directed They Call Him OG (2025), starring Pawan Kalyan?', options: ['Sujeeth', 'Harish Shankar', 'Trivikram Srinivas', 'Krish Jagarlamudi'], answer: 0, explain: 'Sujeeth, who earlier made Saaho with Prabhas, directed OG.' },
      { type: 'mcq', q: 'Which 2025 Hindi film marked Jr. NTR’s Bollywood debut, opposite Hrithik Roshan?', options: ['War 2', 'Fighter', 'Pathaan', 'Tiger 3'], answer: 0, explain: 'Jr. NTR made his Hindi debut in War 2 (2025), part of the YRF Spy Universe.' },
      { type: 'mcq', q: 'Who plays Srivalli, Pushpa’s love interest, in the Pushpa films?', options: ['Rashmika Mandanna', 'Pooja Hegde', 'Samantha Ruth Prabhu', 'Sreeleela'], answer: 0, explain: 'Rashmika Mandanna plays Srivalli opposite Allu Arjun in both films.' },
      { type: 'mcq', q: 'Which director made Game Changer (2025), starring Ram Charan?', options: ['S. Shankar', 'Atlee', 'Lokesh Kanagaraj', 'Mani Ratnam'], answer: 0, explain: 'S. Shankar, known for Enthiran (Robot), directed Game Changer.' },
      { type: 'written', q: 'Fans call Pawan Kalyan by which two-word nickname?', accept: ['power star', 'powerstar', 'the power star'], answerText: 'Power Star', explain: 'Pawan Kalyan has long been known as “Power Star”.' },
      { type: 'written', q: 'Which director, nicknamed “Jakkanna”, made Magadheera, Baahubali and RRR?', accept: ['s s rajamouli', 'ss rajamouli', 'rajamouli', 'koduri srisaila sri rajamouli'], answerText: 'S. S. Rajamouli', explain: 'S. S. Rajamouli is nicknamed “Jakkanna” after a legendary sculptor, for the care he puts into every frame.' },
    ],
    dune: [
      { type: 'mcq', q: 'Who directed Dune: Part One (2021) and Dune: Part Two (2024)?', options: ['Denis Villeneuve', 'Christopher Nolan', 'Ridley Scott', 'David Lynch'], answer: 0, explain: 'Denis Villeneuve directed both films; David Lynch made an earlier Dune in 1984.' },
      { type: 'mcq', q: 'Which actor plays Paul Atreides?', options: ['Timothée Chalamet', 'Austin Butler', 'Tom Holland', 'Oscar Isaac'], answer: 0, explain: 'Timothée Chalamet plays Paul, heir of House Atreides, in both films.' },
      { type: 'mcq', q: 'What is the desert planet at the centre of the story?', options: ['Arrakis', 'Caladan', 'Giedi Prime', 'Salusa Secundus'], answer: 0, explain: 'Arrakis, also called Dune, is the only source of the spice melange.' },
      { type: 'mcq', q: 'Which ocean world is the home of House Atreides?', options: ['Caladan', 'Arrakis', 'Giedi Prime', 'Kaitain'], answer: 0, explain: 'The Atreides leave Caladan when the Emperor hands them Arrakis.' },
      { type: 'mcq', q: 'Who plays Chani, the Fremen warrior Paul falls for?', options: ['Zendaya', 'Florence Pugh', 'Rebecca Ferguson', 'Anya Taylor-Joy'], answer: 0, explain: 'Zendaya plays Chani; Rebecca Ferguson plays Paul’s mother, Lady Jessica.' },
      { type: 'mcq', q: 'Who composed the music for both Dune films?', options: ['Hans Zimmer', 'John Williams', 'Ludwig Göransson', 'Howard Shore'], answer: 0, explain: 'Hans Zimmer won the Oscar for Best Original Score for Dune: Part One.' },
      { type: 'mcq', q: 'Which actor plays Feyd-Rautha Harkonnen in Dune: Part Two?', options: ['Austin Butler', 'Dave Bautista', 'Stellan Skarsgård', 'Josh Brolin'], answer: 0, explain: 'Austin Butler plays the Baron’s ruthless nephew, who duels Paul at the end.' },
      { type: 'mcq', q: 'Which Fremen name, after a small desert mouse, does Paul take?', options: ['Muad’Dib', 'Usul', 'Shai-Hulud', 'Lisan al-Gaib'], answer: 0, explain: 'Muad’Dib is the Fremen word for the desert mouse; inside the sietch, Paul is also called Usul.' },
      { type: 'mcq', q: 'What is the poisoned needle the Reverend Mother holds to Paul’s neck during the pain test?', options: ['The gom jabbar', 'The crysknife', 'The hunter-seeker', 'The maula pistol'], answer: 0, explain: 'The gom jabbar kills anyone who pulls their hand out of the box of pain.' },
      { type: 'mcq', q: 'What do the Fremen plant in the sand to call a sandworm?', options: ['A thumper', 'A stillsuit', 'An ornithopter', 'A shield generator'], answer: 0, explain: 'A thumper’s steady beat draws a worm, which the Fremen can then ride.' },
      { type: 'written', q: 'What is the precious substance, found only on Arrakis, that everyone fights over?', accept: ['spice', 'the spice', 'melange', 'spice melange', 'the spice melange'], answerText: 'Spice', explain: 'The spice melange extends life, expands the mind and makes space travel possible.' },
      { type: 'written', q: 'Who kills Baron Vladimir Harkonnen in Dune: Part Two?', accept: ['paul', 'paul atreides', 'muaddib', 'muad’dib', 'muad dib', 'usul', 'paul muaddib', 'paul muad’dib'], answerText: 'Paul Atreides', explain: 'Paul stabs the Baron at the end of Part Two; in the novel, it is Paul’s sister Alia.' },
    ],
    got: [
      { type: 'mcq', q: 'What is the name of Jon Snow’s white direwolf?', options: ['Ghost', 'Nymeria', 'Summer', 'Grey Wind'], answer: 0, explain: 'Ghost is Jon’s silent white direwolf. Nymeria was Arya’s, Summer was Bran’s and Grey Wind was Robb’s.' },
      { type: 'mcq', q: 'Who kills the Night King in the Battle of Winterfell?', options: ['Arya Stark', 'Jon Snow', 'Daenerys Targaryen', 'Brienne of Tarth'], answer: 0, explain: 'Arya stabs the Night King with a Valyrian steel dagger in season 8.' },
      { type: 'mcq', q: 'Which great house has the words “Hear Me Roar!”?', options: ['House Lannister', 'House Baratheon', 'House Tyrell', 'House Greyjoy'], answer: 0, explain: '“Hear Me Roar!” are the Lannister words, though “A Lannister always pays his debts” is better known.' },
      { type: 'mcq', q: 'Robb Stark and his mother Catelyn are murdered at which event?', options: ['The Red Wedding', 'The Purple Wedding', 'The Battle of the Bastards', 'The Sack of Winterfell'], answer: 0, explain: 'The Red Wedding, at the Twins in season 3, ends Robb’s war.' },
      { type: 'mcq', q: 'Which actor plays Tyrion Lannister?', options: ['Peter Dinklage', 'Nikolaj Coster-Waldau', 'Charles Dance', 'Iain Glen'], answer: 0, explain: 'Peter Dinklage won four Emmys for playing Tyrion.' },
      { type: 'mcq', q: 'What is the name of Arya Stark’s slim sword?', options: ['Needle', 'Longclaw', 'Oathkeeper', 'Ice'], answer: 0, explain: 'Jon Snow gave Arya the sword Needle before she left Winterfell.' },
      { type: 'mcq', q: 'Who is chosen to rule the Six Kingdoms in the series finale?', options: ['Bran Stark', 'Jon Snow', 'Sansa Stark', 'Tyrion Lannister'], answer: 0, explain: 'Bran the Broken becomes king, while Sansa becomes Queen in the North.' },
      { type: 'mcq', q: 'Which character is known as “the Kingslayer”?', options: ['Jaime Lannister', 'Sandor Clegane', 'Jorah Mormont', 'Bronn'], answer: 0, explain: 'Jaime killed the Mad King Aerys II, whom he had sworn to protect.' },
      { type: 'mcq', q: 'Which of Daenerys’s dragons does the Night King kill and raise as an ice dragon?', options: ['Viserion', 'Drogon', 'Rhaegal', 'Balerion'], answer: 0, explain: 'The Night King brings Viserion down with an ice spear beyond the Wall in season 7.' },
      { type: 'mcq', q: 'Hodor’s name comes from which phrase, revealed in season 6?', options: ['Hold the door', 'Hold the horse', 'Hold the hall', 'Hold the road'], answer: 0, explain: 'A vision links young Wylis to the moment Meera shouts “Hold the door!”.' },
      { type: 'written', q: 'Which city is the capital of the Seven Kingdoms and home of the Iron Throne?', accept: ['kings landing', 'king’s landing', 'kingslanding'], answerText: 'King’s Landing', explain: 'The Iron Throne sits in the Red Keep in King’s Landing.' },
      { type: 'written', q: 'Who is called the Mother of Dragons and the Breaker of Chains?', accept: ['daenerys', 'daenerys targaryen', 'dany', 'khaleesi', 'daenerys stormborn'], answerText: 'Daenerys Targaryen', explain: 'Daenerys hatches three dragons and frees the slaves of Slaver’s Bay.' },
    ],
    hotd: [
      { type: 'mcq', q: 'Which actor plays Daemon Targaryen?', options: ['Matt Smith', 'Paddy Considine', 'Rhys Ifans', 'Ewan Mitchell'], answer: 0, explain: 'Matt Smith plays Daemon, Rhaenyra’s uncle and later her husband.' },
      { type: 'mcq', q: 'Who plays the adult Rhaenyra Targaryen after the time jump in season 1?', options: ['Emma D’Arcy', 'Olivia Cooke', 'Milly Alcock', 'Emily Carey'], answer: 0, explain: 'Milly Alcock plays young Rhaenyra, and Emma D’Arcy takes over as the adult princess.' },
      { type: 'mcq', q: 'What is the civil war between the Targaryen “Greens” and “Blacks” called?', options: ['The Dance of the Dragons', 'The War of the Five Kings', 'Robert’s Rebellion', 'The Blackfyre Rebellion'], answer: 0, explain: 'The Dance of the Dragons is the war of succession between Rhaenyra’s Blacks and Aegon II’s Greens.' },
      { type: 'mcq', q: 'Which dragon, the largest one alive, does Aemond Targaryen claim?', options: ['Vhagar', 'Caraxes', 'Syrax', 'Sunfyre'], answer: 0, explain: 'Aemond claims Vhagar, once ridden by Visenya Targaryen and later by Laena Velaryon.' },
      { type: 'mcq', q: 'Which dragon, nicknamed “the Blood Wyrm”, does Daemon ride?', options: ['Caraxes', 'Vermithor', 'Meleys', 'Seasmoke'], answer: 0, explain: 'Daemon rides the red dragon Caraxes, the Blood Wyrm.' },
      { type: 'mcq', q: 'After Viserys I dies, which of Alicent’s sons do the Greens crown king?', options: ['Aegon II', 'Aemond', 'Daeron', 'Jacaerys'], answer: 0, explain: 'Alicent and Otto Hightower crown Aegon II instead of Rhaenyra, the heir Viserys named.' },
      { type: 'mcq', q: 'Who is Hand of the King to Viserys I when the series begins?', options: ['Otto Hightower', 'Lyonel Strong', 'Corlys Velaryon', 'Harwin Strong'], answer: 0, explain: 'Otto Hightower, Alicent’s father, is Hand at the start; Lyonel Strong later replaces him for a time.' },
      { type: 'mcq', q: 'Lord Corlys Velaryon is famous by which nickname, earned on his nine voyages?', options: ['The Sea Snake', 'The Kraken', 'The Sea Dragon', 'The Old Salt'], answer: 0, explain: 'The Sea Snake’s voyages made House Velaryon the richest house in the realm.' },
      { type: 'mcq', q: 'Which character is known as “the Queen Who Never Was”?', options: ['Rhaenys Targaryen', 'Rhaenyra Targaryen', 'Alicent Hightower', 'Laena Velaryon'], answer: 0, explain: 'Rhaenys was passed over for the throne in favour of her cousin Viserys.' },
      { type: 'mcq', q: 'In season 2, Rhaenys dies at Rook’s Rest riding which dragon?', options: ['Meleys', 'Syrax', 'Dreamfyre', 'Vermax'], answer: 0, explain: 'Rhaenys and her dragon Meleys, the Red Queen, fall at Rook’s Rest.' },
      { type: 'written', q: 'What is the name of Rhaenyra’s yellow she-dragon?', accept: ['syrax'], answerText: 'Syrax', explain: 'Rhaenyra rides Syrax, her dragon since she was a girl.' },
      { type: 'written', q: 'Which golden dragon does Aegon II ride?', accept: ['sunfyre', 'sunfire', 'sunfyre the golden'], answerText: 'Sunfyre', explain: 'Aegon II rides Sunfyre, a golden dragon said to be the most beautiful ever seen.' },
    ],
    onepiece: [
      { type: 'mcq', q: 'What is Monkey D. Luffy’s dream?', options: ['To become King of the Pirates', 'To become the world’s greatest swordsman', 'To find the All Blue', 'To draw a map of the whole world'], answer: 0, explain: 'Luffy wants to find the One Piece and become King of the Pirates.' },
      { type: 'mcq', q: 'Which Devil Fruit gave Luffy his rubber body, as it was first named in the story?', options: ['Gum-Gum Fruit', 'Flame-Flame Fruit', 'Chop-Chop Fruit', 'Smoke-Smoke Fruit'], answer: 0, explain: 'The Gum-Gum Fruit (Gomu Gomu no Mi) made Luffy’s body stretch like rubber.' },
      { type: 'mcq', q: 'How many swords does Roronoa Zoro use in his signature fighting style?', options: ['Three', 'Two', 'One', 'Four'], answer: 0, explain: 'Zoro’s Three Sword Style (Santoryu) uses one sword in each hand and one in his mouth.' },
      { type: 'mcq', q: 'Who gave Luffy his straw hat?', options: ['Shanks', 'Garp', 'Whitebeard', 'Gol D. Roger'], answer: 0, explain: 'Red-Haired Shanks left his straw hat with young Luffy as a promise to meet again.' },
      { type: 'mcq', q: 'What is the name of the Straw Hat Pirates’ second ship?', options: ['Thousand Sunny', 'Going Merry', 'Moby Dick', 'Red Force'], answer: 0, explain: 'Franky built the Thousand Sunny after the Going Merry was lost.' },
      { type: 'written', q: 'What is the name of the Straw Hats’ reindeer doctor?', accept: ['chopper', 'tony tony chopper', 'tony chopper'], answerText: 'Tony Tony Chopper', explain: 'Chopper ate the Human-Human Fruit and became the crew’s doctor.' },
      { type: 'mcq', q: 'Which Straw Hat is the crew’s navigator?', options: ['Nami', 'Nico Robin', 'Usopp', 'Franky'], answer: 0, explain: 'Nami is the navigator and dreams of mapping the entire world.' },
      { type: 'mcq', q: 'What is the name of the legendary treasure left behind by Gol D. Roger?', options: ['One Piece', 'Poneglyph', 'Pluton', 'All Blue'], answer: 0, explain: 'Roger’s final words sent the world searching for the One Piece.' },
      { type: 'mcq', q: 'Sanji dreams of finding which legendary sea?', options: ['All Blue', 'Grand Line', 'Red Line', 'Calm Belt'], answer: 0, explain: 'The All Blue is said to hold fish from every sea in the world.' },
      { type: 'written', q: 'Who is Luffy’s sworn brother, known as “Fire Fist”?', accept: ['ace', 'portgas d ace', 'portgas ace', 'portgas d. ace'], answerText: 'Portgas D. Ace', explain: 'Ace ate the Flame-Flame Fruit and sailed with the Whitebeard Pirates.' },
    ],
    naruto: [
      { type: 'mcq', q: 'Which village is Naruto Uzumaki from?', options: ['Hidden Leaf (Konoha)', 'Hidden Sand', 'Hidden Mist', 'Hidden Cloud'], answer: 0, explain: 'Naruto grows up in Konohagakure, the Village Hidden in the Leaves.' },
      { type: 'mcq', q: 'Which tailed beast is sealed inside Naruto?', options: ['The Nine-Tailed Fox', 'The One-Tailed Shukaku', 'The Eight-Tailed Ox', 'The Two-Tailed Cat'], answer: 0, explain: 'The Nine-Tails, Kurama, was sealed into Naruto on the day he was born.' },
      { type: 'mcq', q: 'What is Naruto’s favourite food?', options: ['Ramen', 'Sushi', 'Dango', 'Curry'], answer: 0, explain: 'Naruto’s favourite spot is Ichiraku Ramen.' },
      { type: 'written', q: 'Who is Naruto’s rival on Team 7, from the Uchiha clan?', accept: ['sasuke', 'sasuke uchiha', 'uchiha sasuke'], answerText: 'Sasuke Uchiha', explain: 'Sasuke is Naruto’s rival and best friend.' },
      { type: 'mcq', q: 'Which technique lets Naruto create solid copies of himself?', options: ['Shadow Clone Jutsu', 'Rasengan', 'Chidori', 'Sharingan'], answer: 0, explain: 'The Shadow Clone Jutsu makes real, solid clones — Naruto’s signature move.' },
      { type: 'mcq', q: 'What is Naruto’s lifelong dream?', options: ['To become Hokage', 'To become a Sannin', 'To join the Akatsuki', 'To lead the Anbu'], answer: 0, explain: 'Naruto wants to become Hokage so the whole village will acknowledge him.' },
      { type: 'mcq', q: 'Who is the jonin teacher who leads Team 7?', options: ['Kakashi Hatake', 'Might Guy', 'Asuma Sarutobi', 'Kurenai Yuhi'], answer: 0, explain: 'Kakashi leads Naruto, Sasuke and Sakura.' },
      { type: 'mcq', q: 'The Sharingan is the special eye of which clan?', options: ['Uchiha', 'Hyuga', 'Uzumaki', 'Senju'], answer: 0, explain: 'The Sharingan belongs to the Uchiha; the Hyuga have the Byakugan.' },
      { type: 'mcq', q: 'Which jutsu, created by the Fourth Hokage, did Naruto later master?', options: ['Rasengan', 'Chidori', 'Amaterasu', 'Kamui'], answer: 0, explain: 'Minato Namikaze created the Rasengan; Jiraiya taught it to Naruto.' },
      { type: 'written', q: 'Which toad sage trained Naruto and wrote the Icha Icha books?', accept: ['jiraiya', 'jiraya', 'pervy sage'], answerText: 'Jiraiya', explain: 'Jiraiya, one of the Legendary Sannin, was Naruto’s mentor.' },
    ],
    cricket: [
      { type: 'mcq', q: 'How many players from each team are on the field in a cricket match?', options: ['11', '10', '12', '9'], answer: 0, explain: 'Each side fields eleven players.' },
      { type: 'mcq', q: 'Which player is known as the “God of Cricket”?', options: ['Sachin Tendulkar', 'MS Dhoni', 'Virat Kohli', 'Brian Lara'], answer: 0, explain: 'Sachin Tendulkar scored 100 international centuries.' },
      { type: 'mcq', q: 'How many legal deliveries are there in a standard over?', options: ['6', '5', '8', '4'], answer: 0, explain: 'A standard over has six legal balls.' },
      { type: 'mcq', q: 'Which team won the first Cricket World Cup in 1975?', options: ['West Indies', 'Australia', 'England', 'India'], answer: 0, explain: 'Clive Lloyd’s West Indies beat Australia in the 1975 final at Lord’s.' },
      { type: 'written', q: 'What is it called when a batter is dismissed without scoring a run?', accept: ['duck', 'a duck'], answerText: 'A duck', explain: 'Getting out for zero is called a duck.' },
      { type: 'mcq', q: 'In which year did India win its first Cricket World Cup?', options: ['1983', '2011', '1975', '2007'], answer: 0, explain: 'Kapil Dev’s team beat the West Indies in the 1983 final.' },
      { type: 'mcq', q: 'Which captain led India to the 2007 T20 World Cup, the 2011 World Cup and the 2013 Champions Trophy?', options: ['MS Dhoni', 'Sourav Ganguly', 'Virat Kohli', 'Rahul Dravid'], answer: 0, explain: 'MS Dhoni is the only captain to win all three ICC white-ball trophies.' },
      { type: 'mcq', q: 'What does LBW stand for?', options: ['Leg Before Wicket', 'Long Ball Wide', 'Left Bat Wicket', 'Leg Bye Wide'], answer: 0, explain: 'A batter is out LBW when the ball would have hit the stumps but struck their leg first.' },
      { type: 'mcq', q: 'How many runs are scored when the ball clears the boundary without bouncing?', options: ['6', '4', '5', '8'], answer: 0, explain: 'A six; a ball that bounces before the boundary is worth four.' },
      { type: 'written', q: 'Which T20 league features teams like Chennai Super Kings and Mumbai Indians?', accept: ['ipl', 'indian premier league', 'the ipl'], answerText: 'IPL (Indian Premier League)', explain: 'The Indian Premier League started in 2008.' },
    ],
    football: [
      { type: 'mcq', q: 'How many players does each team have on the pitch?', options: ['11', '10', '12', '9'], answer: 0, explain: 'Each side has eleven players, including the goalkeeper.' },
      { type: 'mcq', q: 'Which country has won the most FIFA World Cups?', options: ['Brazil', 'Germany', 'Italy', 'Argentina'], answer: 0, explain: 'Brazil has won five World Cups.' },
      { type: 'mcq', q: 'Which player is nicknamed “CR7”?', options: ['Cristiano Ronaldo', 'Neymar', 'Kylian Mbappé', 'Lionel Messi'], answer: 0, explain: 'CR7 combines Cristiano Ronaldo’s initials with his shirt number.' },
      { type: 'mcq', q: 'Which country won the 2022 FIFA World Cup in Qatar?', options: ['Argentina', 'France', 'Croatia', 'Brazil'], answer: 0, explain: 'Argentina beat France on penalties in the final.' },
      { type: 'written', q: 'What is it called when one player scores three goals in a match?', accept: ['hat trick', 'hat-trick', 'hattrick', 'a hat trick', 'a hat-trick'], answerText: 'A hat-trick', explain: 'Three goals by one player in a single match is a hat-trick.' },
      { type: 'mcq', q: 'How long is a standard professional football match, not counting stoppage time?', options: ['90 minutes', '60 minutes', '80 minutes', '120 minutes'], answer: 0, explain: 'Two halves of 45 minutes each.' },
      { type: 'mcq', q: 'Which club plays its home matches at Camp Nou?', options: ['FC Barcelona', 'Real Madrid', 'Manchester United', 'Bayern Munich'], answer: 0, explain: 'Camp Nou is FC Barcelona’s home stadium.' },
      { type: 'mcq', q: 'Which card does a referee show to send a player off?', options: ['Red card', 'Yellow card', 'Green card', 'Blue card'], answer: 0, explain: 'A red card means the player must leave the pitch.' },
      { type: 'mcq', q: 'In which country was Lionel Messi born?', options: ['Argentina', 'Spain', 'Portugal', 'Brazil'], answer: 0, explain: 'Messi was born in Rosario, Argentina.' },
      { type: 'written', q: 'What is the name of England’s top professional football league?', accept: ['premier league', 'the premier league', 'epl', 'english premier league'], answerText: 'The Premier League', explain: 'The Premier League has been England’s top division since 1992.' },
    ],
  };

  // Inline SVG figures so questions can carry images without extra files.
  const QUESTION_IMAGES = {
    bst: `<svg class="q-svg" viewBox="0 0 340 210" role="img" aria-label="Binary search tree. Root 8. Its left child is 3, which has children 1 and 6. Its right child is 10, which has a right child 14.">
      <g class="svg-edges">
        <line x1="170" y1="36" x2="95" y2="102"/><line x1="170" y1="36" x2="245" y2="102"/>
        <line x1="95" y1="102" x2="50" y2="170"/><line x1="95" y1="102" x2="140" y2="170"/>
        <line x1="245" y1="102" x2="290" y2="170"/>
      </g>
      <g class="svg-nodes">
        <g transform="translate(170 36)"><circle r="22"/><text>8</text></g>
        <g transform="translate(95 102)"><circle r="22"/><text>3</text></g>
        <g transform="translate(245 102)"><circle r="22"/><text>10</text></g>
        <g transform="translate(50 170)"><circle r="22"/><text>1</text></g>
        <g transform="translate(140 170)"><circle r="22"/><text>6</text></g>
        <g transform="translate(290 170)"><circle r="22"/><text>14</text></g>
      </g>
    </svg>`,
    triangle: `<svg class="q-svg" viewBox="0 0 320 210" role="img" aria-label="Right triangle. The vertical leg is 6, the horizontal leg is 8, and the hypotenuse is labelled x.">
      <polygon class="svg-shape" points="70,170 270,170 70,40"/>
      <polyline class="svg-right" points="70,150 90,150 90,170"/>
      <text class="svg-label" x="48" y="110">6</text>
      <text class="svg-label" x="170" y="198">8</text>
      <text class="svg-label svg-accent" x="186" y="96">x</text>
    </svg>`,
  };

  return { BANK_VERSION, CATEGORIES, SUBJECTS, QUESTION_BANK, QUESTION_IMAGES };
})();
